// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $_middleware from "./routes/_middleware.ts";
import * as $about from "./routes/about.tsx";
import * as $index from "./routes/index.tsx";
import * as $Client from "./islands/Client.tsx";
import * as $NameInput from "./islands/NameInput.tsx";
import * as $PeerList from "./islands/PeerList.tsx";
import * as $SendFile from "./islands/SendFile.tsx";
import * as $TransferList from "./islands/TransferList.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/_middleware.ts": $_middleware,
    "./routes/about.tsx": $about,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/Client.tsx": $Client,
    "./islands/NameInput.tsx": $NameInput,
    "./islands/PeerList.tsx": $PeerList,
    "./islands/SendFile.tsx": $SendFile,
    "./islands/TransferList.tsx": $TransferList,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
